workdir: "/tmp/galaxy"
server:
  port: 8080
database:
  driver: "mysql"
  host: "localhost"
  port: 3306
  dbname: "galaxy"
  user: "root"
  password: ""
github:
  repository: "git@github.com:sioncojp/test-app.git"
  name: "test-app"
url: "test-app.com"
script: "/tmp/hoge.sh"
docker:
  image: "circusd"
  tag: "1.0"
  proxyimage: "galaxy-proxy"
  proxytag: "1.0"
  exec: "/etc/init.d/circusd restart"
